BusTicket.Web/Models/BusExpeditionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BusTicket.Web.Models
{
    public class BusExpeditionViewModel
    {
        public string IdBusExpedition { get; set; }
        public string IdCompany { get; set; }
        public string Company { get; set; }
        public string DepartureDate { get; set; }
        public string DepartureTime { get; set; }
        public string IdDeparturePoint { get; set; }
        public string DeparturePoint { get; set; }
        public string ArrivalPoint { get; set; }
        public string IdArrivalPoint { get; set; }
        public string TicketPrice { get; set; }
        public string Route { get; set; }
        public string BusExpeditionTypeDescription { get; set; }
        public string ExpectedTravelTime { get; set; }
    }
}

BusTicket.Web/Models/ErrorViewModel.cs
using System;

namespace BusTicket.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BusTicket.Web/Models/PnrSearchViewModel.cs
using BusTicket.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BusTicket.Web.Models
{
    public class PnrSearchViewModel
    {
        public Ticket Ticket { get; set; }
    }
}

BusTicket.Web/Models/RoadPointModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BusTicket.Web.Models
{
    public class RoadPointModel
    {
        public string IdRoadPoint { get; set; }
        public string IdTravelCity { get; set; }
        public string Region { get; set; }
        public string PointName { get; set; }
        public string Description { get; set; }
        public string IsCenter { get; set; }
        public string IdConnectedPoint { get; set; }
    }
}

BusTicket.Web/Models/RoadPointViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BusTicket.Web.Models
{
    public class RoadPointViewModel
    {
        public string IdRoadPoint { get; set; }
        public string PointName { get; set; }
    }
}

BusTicket.Web/Controllers/BusExpenditionController.cs
using BusTicket.Web.Interfaces;
using BusTicket.Web.Models;
using BusTicket.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BusTicket.Web.Controllers
{
    public class BusExpenditionController : Controller
    {
        private readonly ILogger<BusExpenditionController> _logger;
        private readonly IBusExpeditionViewModelService _busExpeditionViewModelService;


        public BusExpenditionController(ILogger<BusExpenditionController> logger, IBusExpeditionViewModelService busExpeditionViewModelService)
        {
            _logger = logger;
            _busExpeditionViewModelService = busExpeditionViewModelService;
        }

        public async Task<IActionResult> Expendition(string fromIdRoadPoint, string toIdRoadPoint, DateTime travelDate)
        {
            var busExpeditions = await _busExpeditionViewModelService.GetBusExpeditionAsync(fromIdRoadPoint, toIdRoadPoint, travelDate);

            return View(busExpeditions);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BusTicket.Web/Controllers/HomeController.cs
using BusTicket.Web.Interfaces;
using BusTicket.Web.Models;
using BusTicket.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BusTicket.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRoadPointViewModelService _roadPointViewModelService;


        public HomeController(ILogger<HomeController> logger, IRoadPointViewModelService roadPointViewModelService)
        {
            _logger = logger;
            _roadPointViewModelService = roadPointViewModelService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Search(string fromIdRoadPoint, string toIdRoadPoint, DateTime travelDate)
        {
            return RedirectToAction("Expendition", "BusExpendition", new { 
                @fromIdRoadPoint = fromIdRoadPoint,
                @toIdRoadPoint = toIdRoadPoint,
                @travelDate = travelDate
            });
        }

        [HttpPost]
        public async Task<JsonResult> AutoCompleteAsync(string prefix)
        {
            var points = await _roadPointViewModelService.GetRoadPointsAsync();

            var matchedPoint = (from point in points
                             where point.PointName.StartsWith(prefix)
                             select new
                             {
                                 label = point.PointName,
                                 val = point.IdRoadPoint
                             }).ToList();

            return Json(matchedPoint);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BusTicket.Web/Controllers/PnrSearchController.cs
using BusTicket.Web.Interfaces;
using BusTicket.Web.Models;
using BusTicket.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BusTicket.Web.Controllers
{
    public class PnrSearchController : Controller
    {
        private readonly ILogger<PnrSearchController> _logger;
        private readonly IPnrSearchViewModelService _pnrSearchViewModelService;


        public PnrSearchController(ILogger<PnrSearchController> logger, IPnrSearchViewModelService pnrSearchViewModelService)
        {
            _logger = logger;
            _pnrSearchViewModelService = pnrSearchViewModelService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Search(string pnr)
        {
            var pnrSearchViewModel = _pnrSearchViewModelService.GetPnr(pnr);

            return View(pnrSearchViewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BusTicket.Web/Views/BusExpendition/Expendition.cshtml
@model IEnumerable<BusExpeditionViewModel>
@{
    ViewData["Title"] = "Sefer Listesi";
}

<div class="container">
    <h1>@ViewData["Title"]</h1>

    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>Firma</th>
                    <th>Tarih</th>
                    <th>Saat</th>
                    <th>Nereden</th>
                    <th>Nereye</th>
                    <th>Fiyat</th>
                    <th>Detay</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.Any())
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Company</td>
                            <td>@DateTime.Parse(item.DepartureDate).ToShortDateString()</td>
                            <td>@DateTime.Parse(item.DepartureTime).ToShortTimeString()</td>
                            <td>@item.DeparturePoint</td>
                            <td>@item.ArrivalPoint</td>
                            <td>@item.TicketPrice</td>
                            <td>
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="@("#Detail-"+ item.IdBusExpedition)">Detay</button>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>

    @foreach (var item in Model)
    {
        @await Html.PartialAsync("_DetailPartial", item)
    }
</div>

BusTicket.Web/Views/BusExpendition/_DetailPartial.cshtml
@model BusExpeditionViewModel

@{
    ViewData["Title"] = "Sefer Detay";
}

<div class="modal fade" id="@("Detail-" + Model.IdBusExpedition)" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="travelDetail">Seyehat Detayı</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row mb-3 text-center">
                    <div class="col-6 themed-grid-col">Güzergah</div>
                    <div class="col-6 themed-grid-col">@Model.Route</div>
                </div>
                <div class="row mb-3 text-center">      
                    <div class="col-6 themed-grid-col">Sefer Tipi</div>
                    <div class="col-6 themed-grid-col">@Model.BusExpeditionTypeDescription</div>
                </div>
                <div class="row mb-3 text-center">
                    <div class="col-6 themed-grid-col">Yaklaşık Seyehat Süresi</div>
                    <div class="col-6 themed-grid-col"> @Model.ExpectedTravelTime</div>
                </div>
                
            </div>
        </div>
    </div>
</div>

BusTicket.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Ana Sayfa";
}


<form class="form-signin" asp-action="Search" method="post">
    <div class="text-center mb-4">
        <h1 class="h3 mb-3 font-weight-normal">bTicket</h1>
        <p>Otobüs Bileti Bul.</p>
    </div>

    <div class="form-label-group">
        <label for="fromPoint">Nereden</label>
        <input type="text" id="fromPoint" class="form-control" placeholder="Kalkış yeri" name="fromPointName">
        <input type="hidden" id="hFromPoint" name="fromIdRoadPoint" />

    </div>

    <div class="form-label-group">
        <label for="toPoint">Nereye</label>
        <input type="text" id="toPoint" class="form-control" placeholder="Varış yeri" name="ToPointName">
        <input type="hidden" id="hToPoint" name="toIdRoadPoint" />
    </div>

    <div class="form-label-group">
        <label for="travelDate">Tarih</label>
        <input type="date" id="travelDate" class="form-control" name="travelDate">
    </div>

    <hr />
    <div class="form-label-group">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Ara</button>
    </div>

</form>
@section Scripts{
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.0.min.js" type="text/javascript"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/jquery-ui.min.js" type="text/javascript"></script>
    <link href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/themes/blitzer/jquery-ui.css"
          rel="Stylesheet" type="text/css" />
    <script type="text/javascript">
        $(function () {
            $("#fromPoint").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: '/Home/AutoComplete/',
                        data: { "prefix": request.term },
                        type: "POST",
                        success: function (data) {
                            response($.map(data, function (item) {
                                return item;
                            }))
                        },
                        error: function (response) {
                            alert(response.responseText);
                        },
                        failure: function (response) {
                            alert(response.responseText);
                        }
                    });
                },
                select: function (e, i) {
                    $("#hFromPoint").val(i.item.val);
                },
                minLength: 1
            });
        });
    </script>
    
    <script type="text/javascript">
        $(function () {
            $("#toPoint").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: '/Home/AutoComplete/',
                        data: { "prefix": request.term },
                        type: "POST",
                        success: function (data) {
                            response($.map(data, function (item) {
                                return item;
                            }))
                        },
                        error: function (response) {
                            alert(response.responseText);
                        },
                        failure: function (response) {
                            alert(response.responseText);
                        }
                    });
                },
                select: function (e, i) {
                    $("#hToPoint").val(i.item.val);
                },
                minLength: 1
            });
        });
    </script>
}

BusTicket.Web/Views/PnrSearch/Index.cshtml
@{
    ViewData["Title"] = "Pnr";
}


<form class="form-signin" asp-action="Search" method="get">
    <div class="text-center mb-4">
        <h1 class="h3 mb-3 font-weight-normal">bTicket</h1>
        <p>Pnr Ara.</p>
    </div>

    <div class="form-label-group">
        <label for="pnr">Pnr</label>
        <input type="text" id="pnr" class="form-control" placeholder="Pnr" name="pnr">
    </div>

    <hr />
    <div class="form-label-group">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Ara</button>
    </div>

</form>

BusTicket.Web/Views/PnrSearch/Search.cshtml
@model PnrSearchViewModel
@{
    ViewData["Title"] = "Pnr Sorgula";
}

<div class="container">
    <div class="b-example-divider"></div>
    <h3>Bilet Bigileri</h3>

    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>Pnr</th>
                    <th>Firma</th>
                    <th>Tarih</th>
                    <th>Saat</th>
                    <th>Nereden</th>
                    <th>Nereye</th>
                    <th>Koltuk</th>
                    <th>Fiyat</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.Ticket != null)
                {
                <tr>
                    <td>@Model.Ticket.Pnr</td>
                    <td>@Model.Ticket.Expedition.Company.CompanyName</td>
                    <td>@Model.Ticket.Expedition.TravelDate.GetValueOrDefault().ToShortDateString()</td>
                    <td>@Model.Ticket.Expedition.TravelDate.GetValueOrDefault().ToShortTimeString()</td>
                    <td>@Model.Ticket.DeparturePoint.PointName</td>
                    <td>@Model.Ticket.ArrivalPoint.PointName</td>
                    <td>@Model.Ticket.IdChair</td>
                    <td>@Model.Ticket.Price</td>
                </tr>

                }
            </tbody>
        </table>
    </div>

    <div class="b-example-divider"></div>
    <h3>Yolcu Bigileri</h3>

    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>Yolcu Adı</th>
                    <th>E-Posta</th>
                    <th>Telefon</th>
                    <th>E-Bilet No</th>
                    <th>Servis İsteği</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.Ticket != null)
                {
                    <tr>
                        <td>@Model.Ticket.Passenger.PassengerName</td>
                        <td>@Model.Ticket.Passenger.Email</td>
                        <td>@Model.Ticket.Passenger.Phone</td>
                        <td>@Model.Ticket.EticketNo</td>
                        <td>@Model.Ticket.Service</td>
                    </tr>

                }
            </tbody>
        </table>
    </div>

    <div class="b-example-divider"></div>
    <h3>Sefer Bigileri</h3>

    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>Sefer Süresi</th>
                    <th>Sefer Tipi</th>
                    <th>Sefer No</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.Ticket != null)
                {
                    <tr>
                        <td>@Model.Ticket.Expedition.ExpectedTravelTime</td>
                        <td>@Model.Ticket.Expedition.ExpeditionType.ExpeditionTypeName</td>
                        <td>@Model.Ticket.Expedition.IdExpedition</td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>

BusTicket.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BusTicket.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BusTicket.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PnrSearch" asp-action="Index">Pnr Sorgula</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BusTicket.Web
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>